chore: add github templates
bampakoa/ngx-electronify pull request #2
Opened 2021-01-18 11:40 UTC by Jefiozie

This will add some default templates for issues and add @bampakoa (you) as the default codeowner of a file.

2021-01-18 22:11 UTC, bampakoa requested changes
Thanks for your PR @Jefiozie I have added some comments. Please let me know your thoughts on these.

2021-01-18 22:11 UTC, bampakoa commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: ''
Can we add the built-in `bug` label as the default one? What do you think?

2021-01-18 22:11 UTC, bampakoa commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- Browser [e.g. chrome, safari]
Electron is working with Chromium so I think that the `Browser` option is not applicable in our case.

2021-01-18 22:11 UTC, bampakoa commented on .github/ISSUE_TEMPLATE/feature_request.md
> +labels: ''
Similar to the bug report template, do you think we should add the `enhancement` label as the default one?

2021-01-19 07:14 UTC, Jefiozie commented
Updated this PR with the requested changes.

2021-01-19 16:19 UTC, merged